<?php

namespace app\api\model;
use think\Model;

/**
 * 机器人
 */
class Userrobot extends Model
{
    protected $name = 'user_robot';

    public function getname(){
        $list = [
            "Sheriff ",
            "Kalu",
            "Dammy Jay",
            "Reginald",
            "Evang",
            "Ayoola Olamide",
            "Mory Junior ",
            "Anne Anie",
            "Chinenyes",
            "Fatals",
            "NFL_Memes",
            "Debby Enujuba",
            "Sandra Cowan",
            "Mariam ",
            "Ifeanyi Okere ",
            "Grace Preciou",
            "Faith ",
            "Lydia Shirin ",
            "Djené ",
            "Mambu  Seri",
            "Bangs",
            "Ama Rachie",
            "Promise Murphy",
            "Saidat",
            "Anamakan",
            "Remmy ",
            "Blessing",
            "Victor ",
            "Ekong",
            "Isata Kamara",
            "Mercy",
            "Mhiz Queen",
            "Teabeh Sif",
            "Mbawahs",
            "Riongel Ndadoi ",
            "Jennifer",
            "Finda Macauley",
            "Bella",
            "Michaella Carew",
            "Lass Stanley",
            "Louis Marie",
            "Chisom ",
            "Rema Monet ",
            "Ammar Khalid",
            "Carina Plot",
            "Rosemarie",
            "Lazarus",
            "ABe Nå",
            "Rachel Onekar",
            "Prisca",
            "Mam Sei",
            "Mariama Bah ",
            "Aliame Davis",
            "Grace Precious",
            "Alice Ben",
            "Gladys",
            "Domingo",
            "Kaka Wire",
            "Ramatu Kamara",
            "Sugar",
            "Grace ",
            "Gbendeva",
            "Allies",
            "Lia Smart",
            " Smart",
            "Lilian Samura",
            "Lia Smarts",
            "Amie Sheriff ",
            "Chukwu ",
            "𝐒𝐤𝐲𝐥𝐢𝐚",
            "Favour Nice",
            "Daniel ",
            "Jamal ",
            "Mohamed Cissé",
            "Doussou Traore",
            "John Sekme",
            "Alisha",
            "Aja Joy",
            "Adama Darlyn ",
            "Innocent Chizzy ",
            "Salifou",
            "Chidimma",
            " Kamara",
            "Qwin",
            "Samuel",
            "Kumba",
            "Destiny ",
            "Tinah",
            "Ashabi Gold",
            "Monsters",
            "Chinenye",
            "Perolla Fernandes",
            "Sharkaka",
            "Qwins",
            "Candi Crush",
            "Eti-mfon",
            "warriors",
            "Victor Edet ",
            "Iwuchukwu",
            "Nwodo",
            "Grace Larm",
            "Allie",
            "Angle Nnaji",
            "Mary ",
            "Mambu J",
            "AlumyTech",
            "Amaabai ",
            "David George",
            "Sory Djané",
            "Raymond",
            "Mambu Serita",
            "Sam ",
            "Amaabai Henry",
            "Amarachi",
            "Mercy Emenike",
            "Cesal",
            "Wisdom",
            "Lizzy Udofia",
            "Thanky",
            "Oumar Cherif",
            "Sweet Oge",
            "Debby Enuju",
            "Yeama Bangs",
            "Mariama Dainke",
            "Fatal Kat",
            "Classic",
            "LaDiza Traoré",
            "Grace Nemahun",
            "Koroma ",
            "Marah",
            "Gazelle ",
            "Cynthia",
            "Adama Daboh",
            "Don Billon ",
            "Alima Berthe",
            "Linda Frankk",
            "Vivian",
            "Joshua ",
            "Mahfod",
            "Williamson",
            "Amaka ",
            "Korgho ",
            "Frank",
            "Chinaza Duruaku",
            "Essien",
            "Aminata",
            "Lida Smart",
            "Bose Joy",
            "Mambu J Serite",
            "Adama Adara",
            "Sahr Mbayo",
            "David Nices",
            "Henry",
            "Koroma",
            "Chijioke",
            "joanxchill",
            "Foday Sam",
            "Gabriel",
            "Sharka",
            "Queen Toyosi",
            "Estelle",
            "Glory Demian",
            "Favour",
            "Lizzy",
            "Kalu ",
            "Sekou Traore",
            "Halimatu J ",
            "Jalloh",
            "Opeyemi",
            "Samir",
            "Abiodun",
            "Anelle Mlangeni",
            " Rismoney",
            "Priscilla Johnson",
            "Aisha Katana",
            "Orshi Abigail",
            "Adil Guinea",
            "Destiny Okon",
            "Wilson John ",
            "Godspraise ",
            "Harriet Domingo",
            "Pedro",
            "Lilian Samu",
            "Kadiatu",
            "stAr",
            "ninu",
            "Lassanadiara",
            "Fatal",
            "Ro Sliim",
            "Samuel Alice ",
            "Mohamed Dainkeh",
            "MC Condé",
            "Lia Smart sum",
            " Zuoke ",
            "Chinedu ",
            " Lungay",
            "Wendy Tamalgo ",
            "Fanta Turay",
            "Abraham Kake",
            "Mr_LoLwa",
            "Maigari Babadji",
            "Sillah",
            "Mansaray",
            "Apeke Ade",
            "Djené Diallo",
            "Minh Sah",
            "Freda J Ellis",
            "Umu Kamara",
            "Obinna Nnaji",
            "Rama Mahfod",
            "Christiana",
            "Fanta Fofanah",
            "Dickson",
            "Onyinye",
            "Sesay",
            "Bigboy Abass",
            "Mariame Kaba",
            "Patoranking ",
            "Muinat Oyewole",
            "Djenab Diakite",
            "Fãñtä Kørömä",
            "Fanta Fofan",
            "Ayo Fola",
            "Jaward T",
            "Freda J ",
            " Ayodele",
            "Kadiatu Kunt",
            " Iyabo",
            "onathan",
            "Kidebone",
            "Paulina Terna",
            "Isata Ka",
            "Jules",
            "Favour Ezenwa",
            "Abike Ade",
            "Precious Godspraise",
            "Ejugu Glory ",
            "Buntum ",
            "Motunrayo",
            "Benson ",
            "Bakarr",
            "Princess",
            "Palmer",
            "Junior ",
            "Harriet ",
            "Salissou",
            "Mbawah",
            "Zishe",
            "Larissa Marie",
            "Mmachi Ehirim",
            " Babadee",
            "Michelle Sibande",
            "Glory Aniefiok",
            "Sherif",
            "Mariam Jalloh",
            "Elizie Bakouan",
            "Mizhta P ",
            "Miles",
            "El Bass",
            "Riama",
            "Uchechi Damian",
            "Perolla",
            "Delight",
            " J Ellis",
            "Blossom ",
            "Ajoke Ade",
            "Bigpaps",
            "Roseline Sharka",
            "Solomon Ashiekaa",
            "Jojo",
            "Abdoulaye",
            "Djato",
            "Nannah Binta",
            "Ruth James",
            "Cisse Haigbe",
            "Chiboy",
            "Orji Emma",
            "Abigail ",
            "Aminata Kanneh",
            "Pero Master",
            "Hawa Kunta Koroma",
            "Djibril Idi Djibo",
            "Fanta Allieu",
            "Unique Fidelis",
            "Wendy Ezuma",
            "Esther",
            "Koutoubou Fofana ",
            "Linda Frank",
            "Kadiatu Kunta",
            "Hawa N Yokie ",
            "Patrick Tibbie",
            "Kumbas",
            "She'z Ella",
            "Sardis ",
            "Asa Jesus ",
            "Jaward Tamia",
            "Gabriel 4",
            "Agnes Bankole",
            "Caroline Neale",
            "Koroma Sulay",
            "Zainab Sesay",
            "Olumide Uduak ",
            "Sallay Bankole Mattia",
            "Fofana M'ballou",
            "Essiens",
            "Ugochi Emeka",
            "Thomas ",
            "Michaelnwizu",
            " Tima",
            "Shampoo",
            "Nancy Hadija",
            "David Nice",
            "Amicable",
            "Lusenie",
            "Issa Sheriff",
            "Adara Kargbo",
            "Ashie Ftwi",
            "Jalloh ",
            "Tiana",
            "Roseline ",
            "Mambu J Serita",
            "Safayi Troare",
            "John Beraki",
            "Queency",
            "Imole Abolore",
            "Adama Kallay",
            "Aloke",
            "Junior Bah",
            "Clacci Bee ",
            "Gbendevas",
            " Sylla",
            "Watis Ola",
            "Lanfia Fofana",
            "Mahamadou",
            "Kamara",
            "Isata Gbendeva"
        ];
        return $list;
    }
}
